### ISSUE TITLE
Beat Tracking

### ISSUE THREAD

**Issue by Irinnisar** [slychief/ismir2018_tutorial#4]
Is there a source code for beat tracking, or same with onset detection code?

**Comment by superbock** [comment]
Adapting the tutorial to beat tracking is left as an exercise for the reader ;)

**Comment by Irinnisar** [comment]
Is it to create a split data folder using listing from sklearn.cross_validation import KFold?

**Comment by superbock** [comment]
The splits are there in order to be able to use the same files as in my (and other) papers. Which files you use for training and which for testing is up to you.

**Comment by Irinnisar** [comment]
Are there certain ways or coding that I can learn to make these splits (8 folds)? Then save it to the .fold format.

**Comment by superbock** [comment]
I am really sorry, but I can't help you with that. You have to figure this out by yourself. Please don't get me wrong, but this is not a support forum for problems as fundamental as this one. If you can't solve this problem yourself, you will most likely not be able to train a network, since there are bigger problems to come. Please make yourself familiar with Python and any machine learning framework of your choice first.
